// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nspappmtirfctbdwlgex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zcGFwcG10aXJmY3RiZHdsZ2V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzM5NzYsImV4cCI6MjA2NTU0OTk3Nn0.kEGKrZuBt_nF7xbQolwCXJwT4-sMxefoO8girLVzwcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);